/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import configurations.ConfiguracaoGeral;
import formulariosParametros.FormularioParametrosMediaMovel;
import formulariosParametros.FormularioParametrosPerceptron;
import formulariosParametros.FormularioParametrosSuavExpAjusteTendencia;
import formulariosParametros.FormularioParametrosSuavExpTendenciaSazonalidade;
import formulariosParametros.FormularioParametrosTSKNN;
import javax.swing.JInternalFrame;
import previsao.Previsao;

/**
 *
 * @author rafael
 */
public class FormularioAlgoritmos extends javax.swing.JInternalFrame {

    ConfiguracaoGeral configuracao;
    
     
    public FormularioAlgoritmos() {
        configuracao = new ConfiguracaoGeral();
        
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cMediaMovel = new javax.swing.JCheckBox();
        cSES = new javax.swing.JCheckBox();
        cESTA = new javax.swing.JCheckBox();
        cESTS = new javax.swing.JCheckBox();
        bParametrosMediaMovel = new javax.swing.JButton();
        bParametrosSuavExpSimples = new javax.swing.JButton();
        bParametrosSuavExpTendSazon = new javax.swing.JButton();
        bSuavExpAjTend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cTSKNN = new javax.swing.JCheckBox();
        bParametrosTSKNN = new javax.swing.JButton();
        cPerceptron = new javax.swing.JCheckBox();
        bParametrosPerceptron = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tNumPrevisoes = new javax.swing.JTextField();
        bPrever = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Algoritmos");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritmos"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estatísticos"));

        cMediaMovel.setText("Média Móvel");

        cSES.setText("Suav. Exp. Simples");

        cESTA.setText("Suav. Exp. Ajuste de Tendência");

        cESTS.setText("Suav. Exp. Tend. Sazon.");

        bParametrosMediaMovel.setText("...");
        bParametrosMediaMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParametrosMediaMovelActionPerformed(evt);
            }
        });

        bParametrosSuavExpSimples.setText("...");
        bParametrosSuavExpSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParametrosSuavExpSimplesActionPerformed(evt);
            }
        });

        bParametrosSuavExpTendSazon.setText("...");
        bParametrosSuavExpTendSazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParametrosSuavExpTendSazonActionPerformed(evt);
            }
        });

        bSuavExpAjTend.setText("...");
        bSuavExpAjTend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuavExpAjTendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cMediaMovel)
                        .addGap(126, 126, 126)
                        .addComponent(bParametrosMediaMovel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(cSES)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bParametrosSuavExpSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cESTA)
                                .addComponent(cESTS))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bParametrosSuavExpTendSazon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bSuavExpAjTend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cMediaMovel)
                    .addComponent(bParametrosMediaMovel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cSES)
                    .addComponent(bParametrosSuavExpSimples))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cESTA)
                    .addComponent(bSuavExpAjTend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cESTS)
                    .addComponent(bParametrosSuavExpTendSazon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aprendizado de Máquina"));

        cTSKNN.setText("TSKNN");

        bParametrosTSKNN.setText("...");
        bParametrosTSKNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParametrosTSKNNActionPerformed(evt);
            }
        });

        cPerceptron.setText("Perceptron");

        bParametrosPerceptron.setText("...");
        bParametrosPerceptron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParametrosPerceptronActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cTSKNN)
                    .addComponent(cPerceptron))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bParametrosPerceptron, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(bParametrosTSKNN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTSKNN)
                    .addComponent(bParametrosTSKNN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPerceptron)
                    .addComponent(bParametrosPerceptron))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Avaliação"));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Número de Previsões:");

        tNumPrevisoes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tNumPrevisoes.setText("10");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNumPrevisoes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNumPrevisoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bPrever.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bPrever.setText("Prever");
        bPrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPreverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(bPrever, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bPrever)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPreverActionPerformed

        configuracao.setMediaMovel(cMediaMovel.isSelected());
        configuracao.setSuavExpSimples(cSES.isSelected());
        configuracao.setSuavExpAjusteTendencia(cESTA.isSelected());
        configuracao.setSuavExpTendenciaSazonalidade(cESTS.isSelected());
        configuracao.setTsknn(cTSKNN.isSelected());
        configuracao.setPerceptron(cPerceptron.isSelected());
        configuracao.setNumPrevisoes(Integer.parseInt(tNumPrevisoes.getText()));
        
        Previsao previsao = new Previsao();
        previsao.prever(configuracao);
        

    }//GEN-LAST:event_bPreverActionPerformed

    private void bParametrosMediaMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParametrosMediaMovelActionPerformed
        JInternalFrame frame = new FormularioParametrosMediaMovel(configuracao.getConfiguracaoMediaMovel());
        FormularioPrincipal.getDesktop().add(frame);
        try{
            frame.setSelected(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bParametrosMediaMovelActionPerformed

    private void bParametrosSuavExpSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParametrosSuavExpSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bParametrosSuavExpSimplesActionPerformed

    private void bParametrosPerceptronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParametrosPerceptronActionPerformed
        JInternalFrame frame = new FormularioParametrosPerceptron(configuracao.getConfiguracaoPerceptron());
        FormularioPrincipal.getDesktop().add(frame);
        try{
            frame.setSelected(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bParametrosPerceptronActionPerformed

    private void bParametrosSuavExpTendSazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParametrosSuavExpTendSazonActionPerformed
        JInternalFrame frame = new FormularioParametrosSuavExpTendenciaSazonalidade(configuracao.getConfiguracaoSuavExpTendenciaSazonalidade());
        FormularioPrincipal.getDesktop().add(frame);
        try{
            frame.setSelected(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bParametrosSuavExpTendSazonActionPerformed

    private void bSuavExpAjTendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuavExpAjTendActionPerformed
                
        JInternalFrame frame = new FormularioParametrosSuavExpAjusteTendencia(configuracao.getConfiguracaoSuavExpAjusteTendencia());
        FormularioPrincipal.getDesktop().add(frame);
        try{
            frame.setSelected(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bSuavExpAjTendActionPerformed

    private void bParametrosTSKNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParametrosTSKNNActionPerformed
        JInternalFrame frame = new FormularioParametrosTSKNN(configuracao.getConfiguracaoTSKNN());
        FormularioPrincipal.getDesktop().add(frame);
        try{
            frame.setSelected(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bParametrosTSKNNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bParametrosMediaMovel;
    private javax.swing.JButton bParametrosPerceptron;
    private javax.swing.JButton bParametrosSuavExpSimples;
    private javax.swing.JButton bParametrosSuavExpTendSazon;
    private javax.swing.JButton bParametrosTSKNN;
    private javax.swing.JButton bPrever;
    private javax.swing.JButton bSuavExpAjTend;
    private javax.swing.JCheckBox cESTA;
    private javax.swing.JCheckBox cESTS;
    private javax.swing.JCheckBox cMediaMovel;
    private javax.swing.JCheckBox cPerceptron;
    private javax.swing.JCheckBox cSES;
    private javax.swing.JCheckBox cTSKNN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tNumPrevisoes;
    // End of variables declaration//GEN-END:variables
}
